
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /archives

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/fox.css

# scripts loaded in the end of the body
scripts:
- /js/fox.js

user:
  show: true
  links:
    github:
      url: https://github.com/M-finder
      icon: icon-github
    gitee:
      url: https://gitee.com/M-finder
      icon: icon-gitee
    weibo:
      url: https://weibo.com/p/1005053949818656/home?from=page_100505&mod=TAB&is_all=1#place
      icon: icon-weibo1
    rss:
      url:
      icon:
wordcount: true
article:
  number: 5
cover: /images/cover.jpg
